### ISSUE TITLE
supporters plugin error

### ISSUE THREAD

**Issue by untuned** [papiersnipper/modmail-plugins#2]
```
2019-05-12T20:08:28.689333+00:00 app[worker.1]: bot.py - ERROR: Unexpected exception:
2019-05-12T20:08:28.689347+00:00 app[worker.1]: Traceback (most recent call last):
2019-05-12T20:08:28.689350+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 62, in wrapped
2019-05-12T20:08:28.689352+00:00 app[worker.1]:     ret = await coro(*args, **kwargs)
2019-05-12T20:08:28.689354+00:00 app[worker.1]:   File "/app/plugins/papiersnipper-modmail-plugins/supporters/supporters.py", line 20, in support
2019-05-12T20:08:28.689356+00:00 app[worker.1]:     if c.id != int(category_id):
2019-05-12T20:08:28.689358+00:00 app[worker.1]: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-05-12T20:08:28.689360+00:00 app[worker.1]: 
2019-05-12T20:08:28.689362+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2019-05-12T20:08:28.689363+00:00 app[worker.1]: 
2019-05-12T20:08:28.689364+00:00 app[worker.1]: Traceback (most recent call last):
2019-05-12T20:08:28.689366+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 898, in invoke
2019-05-12T20:08:28.689368+00:00 app[worker.1]:     await ctx.command.invoke(ctx)
2019-05-12T20:08:28.689369+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 615, in invoke
2019-05-12T20:08:28.689371+00:00 app[worker.1]:     await injected(*ctx.args, **ctx.kwargs)
2019-05-12T20:08:28.689373+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 71, in wrapped
2019-05-12T20:08:28.689379+00:00 app[worker.1]:     raise CommandInvokeError(exc) from exc
2019-05-12T20:08:28.689381+00:00 app[worker.1]: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by papiersnipper** [comment]
Hi! Thanks for making an issue, but this isn't a problem with the code. It tries to get the category id of your Modmail bot, but it's not found. Have you ran `?setup`? If you have any questions, feel free to make a comment here or contact me on discord `Papiersnipper#9833`

**Comment by papiersnipper** [comment]
![afbeelding](https://user-images.githubusercontent.com/42642013/57712115-58382500-7670-11e9-9482-fd4eca0c4c6e.png)
